# Wildcard VirtualService for namespace-scoped traffic capture
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wildcard-all-services
spec:
  exportTo:
  - "."  # Only export within the namespace
  gateways:
  - mesh
  hosts:
  # This will match all services in the current namespace
  - "*.svc.cluster.local"
  http:
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
  - route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
      headers:
        request:
          set:
            x-original-host: "%REQ(:AUTHORITY)%"
            x-forwarded-by: envoy-proxy
---
# Direct access to proxy (prevents loops)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: passthrough-proxy-direct
spec:
  exportTo:
  - "."
  hosts:
  - passthrough-proxy
  - passthrough-proxy.svc
  - passthrough-proxy.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
---
# Direct access to collector (prevents loops)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: traffic-collector-direct
spec:
  exportTo:
  - "."
  hosts:
  - traffic-collector
  - traffic-collector.svc
  - traffic-collector.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: traffic-collector
        port:
          number: 9000
