# NOTE: For true namespace isolation, we recommend using Istio Sidecar configuration
# This VirtualService captures traffic but cannot guarantee namespace isolation
# without additional Sidecar configuration
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wildcard-all-services
spec:
  exportTo:
  - "."  # Only export within the namespace
  gateways:
  - mesh
  hosts:
  # This will capture all traffic, but combined with exportTo: "."
  # it should only affect pods in this namespace
  - "*.svc.cluster.local"
  http:
  # Skip if already forwarded by proxy (prevent loops)
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
  # Skip system namespaces to avoid capturing cross-namespace traffic
  - match:
    - uri:
        prefix: "/"
      headers:
        host:
          regex: "^[^.]+\\.(kube-system|kube-public|kube-node-lease|istio-system|istio-config|istio-operator|cert-manager|argocd|monitoring|logging|default)\\.svc\\.cluster\\.local$"
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
  # Skip proxy and collector to prevent loops
  - match:
    - uri:
        prefix: "/"
      headers:
        host:
          regex: "^(passthrough-proxy|traffic-collector).*"
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
  # Route all other traffic through proxy
  - route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
      headers:
        request:
          set:
            x-original-host: "%REQ(:AUTHORITY)%"
            x-forwarded-by: envoy-proxy
---
# Direct access to proxy (prevents loops)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: passthrough-proxy-direct
spec:
  exportTo:
  - "."
  hosts:
  - passthrough-proxy
  - passthrough-proxy.svc
  - passthrough-proxy.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: passthrough-proxy
        port:
          number: 8080
---
# Direct access to collector (prevents loops)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: traffic-collector-direct
spec:
  exportTo:
  - "."
  hosts:
  - traffic-collector
  - traffic-collector.svc
  - traffic-collector.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - headers:
        x-forwarded-by:
          exact: envoy-proxy
    route:
    - destination:
        host: traffic-collector
        port:
          number: 9000
